_target_: lambo.tasks.poli_tasks.poli_task.PoliTask
poli_objective_name: foldx_stability_and_sasa
obj_dim: 2
log_prefix: poli_rfp
batch_size: 16
max_len: 425 
max_num_edits: null
max_ngram_size: 1
allow_len_change: False
num_start_examples: 512
data_path: /Users/rcml/lambo/lambo/assets/foldx/